# .github/workflows/hello.yml
name: Java Hello World CI

# When this workflow should run
on:
  push:
    branches: [ main ]   # Change to 'master' if your default branch is master

# What to do when it runs
jobs:
  build:
    runs-on: ubuntu-latest   # GitHub provides a Linux machine

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java (choose your version)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Compile your HelloWorld.java file
      - name: Compile Java Code
        run: javac src/main/java/com/example/HelloWorld.java

      # Step 4: Run your Hello World program
        # Replace 'com.example.HelloWorld' with your actual package and class name
      - name: Run Java Hello World
        run: java -cp src/main/java/com/example/HelloWorld

