name: Java Hello World CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Compile Java
      - name: Compile Java Code
        run: javac src/main/java/com/example/HelloWorld.java

      # Step 4: Run Java Hello World
      - name: Run Java Hello World
        run: java -cp src/main/java com.example.HelloWorld

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-actions:latest .

      # Step 7: Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-actions:latest

      # Step 8: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # Step 9: Add Kubernetes API DNS mapping (Fix for GitHub Actions DNS issue)
      - name: Add Kubernetes API DNS mapping
        run: |
          echo "3.91.189.117 api.cluster.com" | sudo tee -a /etc/hosts
          echo "✅ Added DNS mapping for api.cluster.com"
          cat /etc/hosts | grep api.cluster.com

      # Step 10: Configure kubeconfig
      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
        shell: bash

      # Step 11: Apply Kubernetes manifest (deployment + service)
      - name: Deploy to Kubernetes
        run: |
          kubectl --kubeconfig $HOME/.kube/config --insecure-skip-tls-verify apply -f k8s-deploy.yml
          kubectl --kubeconfig $HOME/.kube/config --insecure-skip-tls-verify rollout status deployment/hello-world-deployment
        shell: bash

