name: Java Hello World CI/CD to kOps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout your repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Compile Java
      - name: Compile Java Code
        run: javac src/main/java/com/example/HelloWorld.java

      # Step 4: Run Java Hello World
      - name: Run Java Hello World
        run: java -cp src/main/java com.example.HelloWorld

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 6: Build Docker image
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-actions:latest .

      # Step 7: Push Docker image
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-actions:latest

      # Step 8: Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      # Step 9: Install latest kOps CLI dynamically
      - name: Install latest kOps
        run: |
          # Fetch the latest release tag from GitHub
          LATEST=$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
          echo "Latest kOps version: $LATEST"
          curl -Lo kops-linux-amd64 https://github.com/kubernetes/kops/releases/download/$LATEST/kops-linux-amd64
          chmod +x kops-linux-amd64
          sudo mv kops-linux-amd64 /usr/local/bin/kops
          kops version

      # Step 10: Configure kubeconfig for kOps
      - name: Configure kOps kubeconfig
        env:
          KOPS_STATE_STORE: ${{ secrets.KOPS_STATE_STORE }}
          KOPS_CLUSTER_NAME: ${{ secrets.KOPS_CLUSTER_NAME }}
        run: |
          mkdir -p $HOME/.kube
          kops export kubecfg --name $KOPS_CLUSTER_NAME

      # Step 11: Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/hello-world-deployment hello-world-container=${{ secrets.DOCKERHUB_USERNAME }}/hello-world-actions:latest
          kubectl rollout status deployment/hello-world-deployment
        shell: bash

